/**
 * Hand-written mirror of `supabase/migrations`. Kept small and explicit rather
 * than generated, so a schema change that this app cares about fails to compile
 * instead of failing at runtime.
 */

export type TaskRow = {
  id: string;
  user_id: string;
  /** `YYYY-MM`. */
  month: string;
  name: string;
  target: number;
  color: string;
  icon: string;
  created_at: string;
  updated_at: string;
};

export type TaskCompletionRow = {
  id: string;
  user_id: string;
  task_id: string;
  /** `YYYY-MM-DD`. */
  date: string;
  created_at: string;
};

export type TimeSessionRow = {
  id: string;
  user_id: string;
  task_id: string;
  start_time: string;
  end_time: string;
  /** Generated by Postgres from the two instants; never written by the client. */
  duration_seconds: number;
  created_at: string;
  updated_at: string;
};

export type ActiveTimerRow = {
  user_id: string;
  task_id: string;
  start_time: string;
  month: string;
  created_at: string;
};

export type ProfileRow = {
  id: string;
  display_name: string;
  email: string;
  created_at: string;
  updated_at: string;
};

export type LeaderboardTimeRow = {
  rank: number;
  user_id: string;
  display_name: string;
  total_seconds: number;
  session_count: number;
};

export type LeaderboardCompletionRow = {
  rank: number;
  user_id: string;
  display_name: string;
  completion_count: number;
};

type Table<Row, Insert = Row, Update = Partial<Row>> = {
  Row: Row;
  Insert: Insert;
  Update: Update;
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      profiles: Table<
        ProfileRow,
        { id: string; display_name: string; email: string },
        { display_name?: string }
      >;
      tasks: Table<
        TaskRow,
        {
          id?: string;
          user_id: string;
          month: string;
          name: string;
          target: number;
          color: string;
          icon: string;
          created_at?: string;
        },
        { name?: string; target?: number; color?: string; icon?: string }
      >;
      task_completions: Table<
        TaskCompletionRow,
        { id?: string; user_id: string; task_id: string; date: string }
      >;
      time_sessions: Table<
        TimeSessionRow,
        {
          id?: string;
          user_id: string;
          task_id: string;
          start_time: string;
          end_time: string;
          created_at?: string;
        }
      >;
      active_timers: Table<
        ActiveTimerRow,
        { user_id: string; task_id: string; start_time: string; month: string }
      >;
    };
    Views: Record<never, never>;
    Functions: {
      leaderboard_time: {
        Args: { p_month: string };
        Returns: LeaderboardTimeRow[];
      };
      leaderboard_completions: {
        Args: { p_month: string };
        Returns: LeaderboardCompletionRow[];
      };
      start_timer: {
        Args: { p_task_id: string; p_month: string };
        Returns: ActiveTimerRow;
      };
    };
    Enums: Record<never, never>;
    CompositeTypes: Record<never, never>;
  };
}
